# Form implementation generated from reading ui file 'app_template.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_app_template_format(object):
    def setupUi(self, app_template_format):
        app_template_format.setObjectName("app_template_format")
        app_template_format.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(app_template_format)
        self.gridLayout.setObjectName("gridLayout")
        self.app_image = QtWidgets.QFrame(parent=app_template_format)
        self.app_image.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.app_image.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.app_image.setObjectName("app_image")
        self.gridLayout.addWidget(self.app_image, 0, 0, 1, 3)
        self.settings_button = QtWidgets.QPushButton(parent=app_template_format)
        self.settings_button.setFlat(True)
        self.settings_button.setObjectName("settings_button")
        self.gridLayout.addWidget(self.settings_button, 1, 2, 1, 1)
        self.progress_bar = QtWidgets.QProgressBar(parent=app_template_format)
        self.progress_bar.setEnabled(True)
        self.progress_bar.setProperty("value", 50)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout.addWidget(self.progress_bar, 2, 0, 1, 3)
        self.about_button_3 = QtWidgets.QPushButton(parent=app_template_format)
        self.about_button_3.setFlat(True)
        self.about_button_3.setObjectName("about_button_3")
        self.gridLayout.addWidget(self.about_button_3, 1, 0, 1, 1)
        self.install_button = QtWidgets.QPushButton(parent=app_template_format)
        self.install_button.setFlat(True)
        self.install_button.setObjectName("install_button")
        self.gridLayout.addWidget(self.install_button, 1, 1, 1, 1)

        self.retranslateUi(app_template_format)
        QtCore.QMetaObject.connectSlotsByName(app_template_format)

    def retranslateUi(self, app_template_format):
        _translate = QtCore.QCoreApplication.translate
        app_template_format.setWindowTitle(_translate("app_template_format", "Form"))
        self.settings_button.setText(_translate("app_template_format", "Settings"))
        self.about_button_3.setText(_translate("app_template_format", "About"))
        self.install_button.setText(_translate("app_template_format", "Install"))
